name: Cypress Tests with Slack Notification

run-name: "Cypress run for Sample2 test on ${{ github.ref }} by ${{ github.actor }}"

on:
  push:
  schedule:
    #This cron will never run (Feb 30th does not exist)
    - cron: '0 0 30 2 *'

jobs:
  sample2-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run Sample2 Cypress test
        env:
          TERM: dumb
        run: |
          npx cypress run \
          --spec cypress/e2e/sample2.cy.ts \
          --headed --browser chrome
      - name: Slack Notification - Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            * ✅ Cypress test run for sample2 test succeeded!*
          SLACK_COLOR: good
      - name: Slack Notification - Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            * ❌ Cypress test run for sample2 test failed!*
          SLACK_COLOR: danger
